#!/bin/sh

docker build -t natpass -f contrib/build/Dockerfile .
docker run --rm \
   -v `pwd`:/build \
   -v $HOME/.cache/go-build:/root/.cache/go-build \
   -v $HOME/go/pkg/mod:/root/go/pkg/mod \
   natpass go run /build/contrib/build/build_all.go